version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bookcoop_db
    restart: always
    environment:
      - POSTGRES_DB=bookcoop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gjitkyf[eq102
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend/nuxt-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/nuxt-app:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/target
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://postgres:Gjitkyf[eq102@db:5432/bookcoop
    command: cargo run
    depends_on:
      - db

volumes:
  postgres_data: